#!/bin/bash

set -e

if [ -z "${USER}" ]
then
	echo "USER env var is not set, please fix"
	exit 1
fi

if [ -z "${ACR_NAME}" -o -z "${AZURE_SUBSCRIPTION_ID}" ]
then
	echo "some env vars are missing, please run az-env first"
	exit 1
fi

az acr login --name "${ACR_NAME}" --subscription "${AZURE_SUBSCRIPTION_ID}"
